add setup

diff --git a/.github/workflows/build-apk.yaml b/.github/workflows/build-apk.yaml
--- a/.github/workflows/build-apk.yaml
+++ b/.github/workflows/build-apk.yaml
@@ -44,15 +44,20 @@ jobs:
           echo "No pubspec.yaml found. Skipping clean step."
         fi
 
+    - name: Install Build Tools
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y build-essential python3-dev
+
     - name: Setup Python ${{ env.PYTHON_VERSION }}
       uses: actions/setup-python@v5
       with:
         python-version: ${{ env.PYTHON_VERSION }}
 
-    - name: Install Python Dependencies
+    - name: Upgrade Pip and Install Python Dependencies
       run: |
-        echo "Upgrading pip and installing requirements..."
-        python -m pip install --upgrade pip || { echo "Failed to upgrade pip"; exit 1; }
+        echo "Upgrading pip and setuptools..."
+        python -m pip install --upgrade pip setuptools || { echo "Failed to upgrade pip or setuptools"; exit 1; }
         pip install -r requirements.txt || { echo "Failed to install requirements"; exit 1; }
 
     - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
@@ -80,7 +85,7 @@ jobs:
       run: |
         echo "Starting APK and AAB build..."
         echo "Running flet build apk command..."
-        flet build apk --build-version ${{ env.BUILD_VERSION }} --build-number ${{ env.BUILD_NUMBER }} --verbose
+        flet build apk --build-version ${{ env.BUILD_VERSION }} --build-number ${{ env.BUILD_NUMBER }} --verbose > apk_build.log 2>&1
         if [ $? -ne 0 ]; then
           echo "Flet build apk failed. Check apk_build.log for details."
           exit 1
