updae

diff --git a/.github/workflows/build_apk_abb.yaml b/.github/workflows/build_apk_abb.yaml
--- a/.github/workflows/build_apk_abb.yaml
+++ b/.github/workflows/build_apk_abb.yaml
@@ -27,31 +27,29 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v4
 
-    - name: Clean Build Directory (if pubspec.yaml found)
-      run: |
-        echo "Checking for pubspec.yaml..."
-        if [ -f "pubspec.yaml" ]; then
-          echo "pubspec.yaml found. Checking if Flutter is available..."
-          if command -v flutter >/dev/null 2>&1; then
-            echo "Flutter found. Cleaning build directory..."
-            flutter clean || { echo "Flutter clean failed"; exit 1; }
-          else
-            echo "Flutter not found. Skipping clean step."
-          fi
-          echo "Removing build directory..."
-          rm -rf build || { echo "Failed to remove build directory"; exit 1; }
-        else
-          echo "No pubspec.yaml found. Skipping clean step."
-        fi
-
     - name: Setup Python ${{ env.PYTHON_VERSION }}
       uses: actions/setup-python@v5
       with:
         python-version: ${{ env.PYTHON_VERSION }}
-
+    - name: Clean Build Directory
+      run: |
+          echo "Checking for pubspec.yaml..."
+          if [ -f "pubspec.yaml" ]; then
+            echo "pubspec.yaml found. Checking if Flutter is available..."
+            if command -v flutter >/dev/null 2>&1; then
+              echo "Flutter found. Cleaning build directory..."
+              flutter clean || { echo "Flutter clean failed"; exit 1; }
+            else
+              echo "Flutter not found. Skipping Flutter clean step."
+            fi
+            echo "Removing build directory..."
+            rm -rf build || { echo "Failed to remove build directory"; exit 1; }
+          else
+            echo "No pubspec.yaml found. Skipping clean step."
+          fi
     - name: Install Python Dependencies
       run: |
-        echo "Installing Python dependencies..."
+        echo "Upgrading pip and installing requirements..."
         python -m pip install --upgrade pip || { echo "Failed to upgrade pip"; exit 1; }
         pip install -r requirements.txt || { echo "Failed to install requirements"; exit 1; }
 
@@ -66,9 +64,11 @@ jobs:
         distribution: 'temurin'
         java-version: '21'
 
+    
+
     - name: Verify Flutter Installation
       run: |
-        echo "Checking Flutter version..."
+        echo "Checking Flutter installation..."
         flutter --version || { echo "Flutter command failed"; exit 1; }
 
     - name: Configure Flutter
