add verbose to build

diff --git a/.github/workflows/build_apk_abb.yaml b/.github/workflows/build_apk_abb.yaml
--- a/.github/workflows/build_apk_abb.yaml
+++ b/.github/workflows/build_apk_abb.yaml
@@ -80,9 +80,9 @@ jobs:
       run: |
         echo "Starting APK and AAB build..."
         echo "Running flet build apk command..."
-        flet build apk --build-version ${{ env.BUILD_VERSION }} --build-number ${{ env.BUILD_NUMBER }} --verbose || { echo "Flet build apk failed"; exit 1; }
+        flet build apk --build-version ${{ env.BUILD_VERSION }} --build-number ${{ env.BUILD_NUMBER }} --verbose > apk_build.log 2>&1 || { echo "Flet build apk failed"; cat apk_build.log; exit 1; }
         echo "Running flet build aab command..."
-        flet build aab --build-version ${{ env.BUILD_VERSION }} --build-number ${{ env.BUILD_NUMBER }} --verbose || { echo "Flet build aab failed"; exit 1; }
+        flet build aab --build-version ${{ env.BUILD_VERSION }} --build-number ${{ env.BUILD_NUMBER }} --verbose > aab_build.log 2>&1 || { echo "Flet build aab failed"; cat aab_build.log; exit 1; }
 
     - name: List All Files in Build Directory
       run: |
