Update build_apk_abb.yaml

diff --git a/.github/workflows/build_apk_abb.yaml b/.github/workflows/build_apk_abb.yaml
--- a/.github/workflows/build_apk_abb.yaml
+++ b/.github/workflows/build_apk_abb.yaml
@@ -16,9 +16,10 @@ env:
   BUILD_VERSION: 1.0.0
   PYTHON_VERSION: 3.12.2
   FLUTTER_VERSION: 3.24.0
+  SDK_VERSION: 35
+  BUILD_TOOLS_VERSION: 34
   APK_PATH: "build/apk/app-release.apk"
   AAB_PATH: "build/aab/app-release.aab"
-  ANDROID_HOME: /usr/local/android-sdk
 
 jobs:
   build-apk:
@@ -27,36 +28,6 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v4
-
-    - name: Install System Dependencies for Linux Development
-      run: |
-        echo "Installing system dependencies..."
-        sudo apt-get update
-        sudo apt-get install -y ninja-build libgtk-3-dev
-
-    - name: Install Android SDK Command Line Tools
-      run: |
-        echo "Installing Android SDK Command Line Tools..."
-        mkdir -p $ANDROID_HOME/cmdline-tools
-        cd $ANDROID_HOME/cmdline-tools
-        curl -O https://dl.google.com/android/repository/commandlinetools-linux-6858067_latest.zip
-        unzip commandlinetools-linux-6858067_latest.zip
-        rm commandlinetools-linux-6858067_latest.zip
-
-    - name: Install Android SDK Platform Tools
-      run: |
-        echo "Installing Android SDK platform tools..."
-        yes | sdkmanager --licenses
-        sdkmanager "platform-tools"
-
-    - name: Setup Android Home Environment Variable
-      run: echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
-
-    - name: Install Android SDK Packages
-      run: |
-        echo "Installing Android SDK packages..."
-        yes | sdkmanager --licenses
-        sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"
 
     - name: Setup Python ${{ env.PYTHON_VERSION }}
       uses: actions/setup-python@v5
@@ -78,6 +49,12 @@ jobs:
       with:
         distribution: 'temurin'
         java-version: '21'
+
+    - name: Setup Android SDK and Build Tools
+      uses: android-actions/setup-android@v1
+      with:
+        sdk-version: ${{ env.SDK_VERSION }}
+        build-tools: ${{ env.BUILD_TOOLS_VERSION }}
 
     - name: Clean Build Directory and Flutter
       run: |
@@ -115,6 +92,16 @@ jobs:
           echo "No pubspec.yaml found. Skipping APK build."
         fi
 
+    - name: Flet Build AAB
+      run: |
+        if [ -f "pubspec.yaml" ]; then
+          echo "Starting Flet AAB build..."
+          flet build aab --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION 2>&1 | tee flet_build.log
+          echo "Flet AAB build completed."
+        else
+          echo "No pubspec.yaml found. Skipping AAB build."
+        fi
+
     - name: List All Files in Build Directory
       run: |
         if [ -d "build" ]; then
@@ -124,8 +111,8 @@ jobs:
           echo "Build directory does not exist. Skipping file listing."
         fi
 
-    - name: Verify APK Existence
-      id: verify-apk
+    - name: Verify APK and AAB Existence
+      id: verify-files
       run: |
         if [ -f "$APK_PATH" ]; then
           echo "APK file found at $APK_PATH"
@@ -134,11 +121,26 @@ jobs:
           echo "Error: APK file not found at $APK_PATH!"
           exit 1
         fi
+        if [ -f "$AAB_PATH" ]; then
+          echo "AAB file found at $AAB_PATH"
+          echo "AAB_PATH=$AAB_PATH" >> $GITHUB_ENV
+        else
+          echo "Error: AAB file not found at $AAB_PATH!"
+          exit 1
+        fi
 
     - name: Upload APK Artifact
       uses: actions/upload-artifact@v4.3.4
       with:
         name: apk-build-artifact
-        path: ${{ env.APK_PATH }}
-        if-no-files-found: error
+        path: build/apk
+        if-no-files-found: warn
+        overwrite: false
+
+    - name: Upload AAB Artifact
+      uses: actions/upload-artifact@v4.3.4
+      with:
+        name: aab-build-artifact
+        path: build/aab
+        if-no-files-found: warn
         overwrite: false
