Update build_apk_abb.yaml

diff --git a/.github/workflows/build_apk_abb.yaml b/.github/workflows/build_apk_abb.yaml
--- a/.github/workflows/build_apk_abb.yaml
+++ b/.github/workflows/build_apk_abb.yaml
@@ -1,33 +1,23 @@
 name: All Builds (Linux, macOS, Windows, Android, IPA, APK, AAB)
 
 on:
-  # Runs on push to any of the below branches
   push:
     branches:
       - master
       - main
-  # Runs on pull request events that target one of the below branches
   pull_request:
     branches:
       - master
       - main
-
-  # Allows you to run this workflow manually from the Actions tab of the repository
   workflow_dispatch:
 
 env:
-  # https://flet.dev/docs/publish#versioning
   BUILD_NUMBER: 1
   BUILD_VERSION: 1.0.0
   PYTHON_VERSION: 3.12.2
   FLUTTER_VERSION: 3.24.0
 
 jobs:
-  
-  
-
-  
-
   build-apk:
     runs-on: ubuntu-latest
 
@@ -58,14 +48,20 @@ jobs:
 
     - name: Flet Build APK
       run: |
+        echo "Configuring Flutter"
         flutter config --no-analytics
-        flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION
+        
+        echo "Starting Flet APK build"
+        flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION || {
+          echo "Flet APK build failed. See the error details above.";
+          exit 1;
+        }
 
     - name: Upload APK Artifact
+      if: success()
       uses: actions/upload-artifact@v4.3.4
       with:
         name: apk-build-artifact
         path: build/apk
         if-no-files-found: warn
         overwrite: false
-
